version: '2'

services:
  web:
    #image: node:latest
    build: .
    ports:
    - "3001:8080"
    volumes:
      - ./:/fullsd
    depends_on:
    - mongo
  mongo:
    container_name: mongo_container
    image: mongo:latest
    container_name: db
    expose:
      - '27017'
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
  

volumes:
  db_data:
