version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: db
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db
  web:
    image: node:latest
    build:
     context: ./
    user: "node"
    volumes:
      - ./:/fullsd
    ports:
      - 4200:80
    links:
      - mongodb

volumes:
  db_data:
